# This file contains default configuration settings for the Redfish Protocol Validator
# All settings can be overridden by command-line arguments

[Authentication]
# The username for authentication (required if not provided via command line)
user = 

# The password for authentication (required if not provided via command line)
password = 

[Connection]
# The IP address (and port) of the Redfish service (required if not provided via command line)
# Example: https://RedfishIP
rhost = 

# Disable verification of host SSL certificates (true/false)
no-cert-check = true

# The file or directory containing trusted CAs
# Leave empty if not needed
ca-bundle = 

# Avoid attempts to generate HTTP redirects for services that do not support HTTP (true/false)
avoid-http-redirect = false

[Logging]
# The logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log-level = WARNING

[Reporting]
# The directory for generated report files
report-dir = reports

# The type of report to generate (html, tsv, both)
report-type = both